# Test 3: full-multi-column-transfer
[settings.general]
protocol_name = "full-multi-column-transfer"
mode = "multi"
starting_tip_well = "H1"
tip_reuse = "always"

[settings.general.head_speed]
speed = 400

[settings.liquid_handling]
active_preset = ""

[settings.liquid_handling.pre_aspirate_contact]
enabled = true
position_offset_percent = 20
aspirate_volume = 0

[settings.liquid_handling.post_aspirate_wick]
enabled = true
radius = 0.8
v_offset_mm = -1.5
speed = 20

[settings.liquid_handling.delays]
post_aspirate = 0

[settings.liquid_handling.push_out]
enabled = false

[settings.liquid_handling.mixing]
enabled = true
location = "destination"
repetitions = 3
source_remixing = "once"

[[settings.working_plate]]
type = "source"
labware_id = "tube_rack_96_1500ul"
position_rack = "4"

[[settings.working_plate]]
type = "destination"
labware_id = "384_ppv_55ul"
position_rack = "2"

[[settings.working_plate]]
type = "tip"
labware_id = "opentrons_96_tiprack_300ul"
connection = "Pipette_8"
position_rack = "5"
